title: "Le site de David Bruant"
author: "David Bruant"
description: "site web/blog de David Bruant"
url: "https://davidbruant.github.io"

collections:
  projects:
    output: true

plugins:
  - jekyll-feed

markdown: CommonMark
commonmark:
  options: ["FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

theme: mimoza

scribouilli: true

# i_know_what_i_am_doing: true

optional_front_matter: 
  remove_originals: false
