backend:
  name: github
  repo: davidbruant/davidbruant.github.io

media_folder: "images"

collections:
  - label: "Blog"
    name: "blog"
    folder: "."
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}